"""add google_id to users

Revision ID: ab527cfce002
Revises: 
Create Date: 2026-09-24 10:14:05.966029

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab527cfce002'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('evaluations', sa.Column('status', sa.String(length=50), server_default='completed', nullable=False))
    op.alter_column('evaluations', 'overall_score',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('users', sa.Column('google_id', sa.String(length=255), nullable=True))
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.create_index(op.f('ix_users_google_id'), 'users', ['google_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_google_id'), table_name='users')
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_column('users', 'google_id')
    op.alter_column('evaluations', 'overall_score',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('evaluations', 'status')
    # ### end Alembic commands ###
